module.exports = {
    WEBSOCKET_EVENT_JOIN: 'WEBSOCKET_EVENT_JOIN',
    WEBSOCKET_EVENT_DISCONNECTED: 'WEBSOCKET_EVENT_DISCONNECTED',
    WEBSOCKET_EVENT_SELECT: 'WEBSOCKET_EVENT_SELECT',
    WEBSOCKET_EVENT_SET_OPTION: 'WEBSOCKET_EVENT_SET_OPTION'
};
